# Generated by Django 4.2.3 on 2023-08-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_profile_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
