# Generated by Django 4.2.3 on 2023-08-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_comment_profile_id_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
