# Generated by Django 4.2.3 on 2023-08-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_rename_profile_id_comment_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createdAt',
            new_name='date',
        ),
    ]
