# Generated by Django 3.2.10 on 2023-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_sentence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencesubject',
            name='subject_color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
