# Generated by Django 4.2.3 on 2023-10-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_sentence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsentence',
            name='answer',
        ),
    ]
