# Generated by Django 4.2.3 on 2023-10-01 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_american', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, default="I'm New!", max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('points', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('questions_answered_correctly', models.ManyToManyField(blank=True, null=True, to='quiz_american.quizamerican')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
