# Generated by Django 4.2.3 on 2023-10-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_sentence', '0003_quizsentenceanswer'),
        ('profile_user', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questions_answered_correctly_sentencequiz',
            field=models.ManyToManyField(blank=True, null=True, to='quiz_sentence.quizsentence'),
        ),
    ]
