# Generated by Django 4.2.3 on 2023-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.TextField(),
        ),
    ]
