# Generated by Django 4.2.3 on 2023-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizvoice',
            name='question',
            field=models.FileField(upload_to=''),
        ),
    ]
