# Generated by Django 3.2.10 on 2023-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_american', '0002_americansubject_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='americansubject',
            name='subject_color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
